/**
 * Turns the client's raw WhatsApp photos into web-ready assets.
 *
 * Furnishing sites live or die on image weight — the originals are 8.2 MB of
 * full-resolution JPEG, which on a Thane 4G connection is a several-second
 * blank screen. For every entry in the manifest this writes:
 *
 *   public/images/<name>.webp        max 1600px on the long edge — lightbox
 *   public/images/<name>-800.webp    max  800px — the gallery grid
 *   public/images/<name>-400.webp    max  400px — mobile grid / srcset floor
 *
 * Dimensions of the 1600px render are written back into
 * `src/data/gallery.gen.js` so every <img> can carry width/height and reserve
 * its own space — no layout shift while the grid loads.
 *
 * Run with `npm run images`. Safe to re-run; it overwrites in place.
 */
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import { IMAGES } from './image-manifest.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = join(ROOT, 'client-images')
const OUT_DIR = join(ROOT, 'public', 'images')

const WIDTHS = [
  { suffix: '', width: 1600, quality: 80 },
  { suffix: '-800', width: 800, quality: 78 },
  { suffix: '-400', width: 400, quality: 72 },
]

async function main() {
  await mkdir(OUT_DIR, { recursive: true })

  const available = new Set(await readdir(SRC_DIR))
  const missing = IMAGES.filter((i) => !available.has(i.src))
  if (missing.length) {
    console.error('\n✗ These manifest entries have no source file:')
    missing.forEach((m) => console.error(`   ${m.src}`))
    process.exit(1)
  }

  const generated = []
  let srcBytes = 0
  let outBytes = 0

  for (const img of IMAGES) {
    const srcPath = join(SRC_DIR, img.src)
    srcBytes += (await stat(srcPath)).size

    let meta = null

    for (const { suffix, width, quality } of WIDTHS) {
      // .rotate() with no argument honours the EXIF orientation tag; passing a
      // number instead applies a hard rotation, which is what the handful of
      // sideways WhatsApp photos need.
      let pipeline = sharp(srcPath).rotate(img.rotate ?? undefined)

      pipeline = pipeline
        .resize({ width, height: width, fit: 'inside', withoutEnlargement: true })
        .webp({ quality, effort: 5 })

      const outPath = join(OUT_DIR, `${img.name}${suffix}.webp`)
      const info = await pipeline.toFile(outPath)
      outBytes += info.size
      if (suffix === '') meta = { width: info.width, height: info.height }
    }

    generated.push({ ...img, ...meta })
    process.stdout.write('.')
  }

  const file = `/**
 * GENERATED by scripts/process-images.mjs — do not edit by hand.
 * Edit scripts/image-manifest.mjs and run \`npm run images\` instead.
 */
export const GALLERY = ${JSON.stringify(
    generated.map(({ src, ...keep }) => keep),
    null,
    2,
  )}
`
  await writeFile(join(ROOT, 'src', 'data', 'gallery.gen.js'), file, 'utf8')

  const mb = (b) => (b / 1024 / 1024).toFixed(2)
  console.log(`\n\n✓ ${generated.length} photos → ${generated.length * 3} WebP files`)
  console.log(`  originals ${mb(srcBytes)} MB → all renditions ${mb(outBytes)} MB`)
  console.log('  wrote src/data/gallery.gen.js')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
